#!/usr/bin/env node

const fs = require("fs");
const osm2geojson = require('./lib/index.js');

const data = fs.readFileSync("/dev/stdin", "utf-8");

const geojson = osm2geojson(data, {});

process.stdout.write(JSON.stringify(geojson));
