#!/usr/bin/env node

const osm2geojson = require('./lib/index.js');
const fs = require('fs');

const data = fs.readFileSync("/dev/stdin", "utf-8");
const geojson = osm2geojson(data, {completeFeature: true, renderTagged: true});
console.log(JSON.stringify(geojson));